- hosts: service
  remote_user: vagrant
  sudo: yes
  vars:
    - container_image: api
    - server_match: api.*
    - container_name: api-service
    - http_address: /
    - has_db: true
  roles:
    - docker
    - consul
    - swarm
    - nginx
    - service